### ISSUE TITLE
Programmers add their own markdown page in the coders folder

### ISSUE THREAD

**Issue by sidgupta234** [sid21g/30daysofcode#3]

**Comment by FleetAdmiral** [comment]
@sidgupta234 Didn't get the gist of the issue. What's to be expected here?

**Comment by sidgupta234** [comment]
Kindly read our Readme, in order to understand the project. :) You can create pull requests to join our initiative.

**Comment by sidgupta234** [comment]
Kindly read our Readme, in order to understand the project. :) You can create pull requests to join our initiative.

**Comment by kzisme** [comment]
@sidgupta234  It can be any markdown page?  I'm a little confused by what you're looking for.

**Comment by sidgupta234** [comment]
Read our Readme, in order to understand the project. You can create pull requests to join our initiative. Inspired from https://github.com/coding-blocks/make-a-pr/issues/1
